In [41]:
import pandas as pd
import glob
import os

## Data Loading

In [42]:
all_dfs = []
for filename in glob.glob("../data/*.csv"):
    new_df = pd.read_csv(filename)
    all_dfs.append(new_df)
df = pd.concat(all_dfs)

In [4]:
df.to_parquet("../data/raw_data.parquet", index=False)

In [5]:
df = pd.read_parquet("../data/raw_data.parquet")

In [6]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,...,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,9/1/2025 12:00:00 AM,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,...,0.0,0.0,359.0,2475.0,10,NaN,NaN,NaN,NaN,NaN
1,9/1/2025 12:00:00 AM,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,...,0.0,0.0,334.0,2475.0,10,NaN,NaN,NaN,NaN,NaN
2,9/1/2025 12:00:00 AM,AA,1002,MSN,"Madison, WI",WI,Wisconsin,CLT,"Charlotte, NC",NC,...,0.0,0.0,134.0,708.0,3,NaN,NaN,NaN,NaN,NaN
3,9/1/2025 12:00:00 AM,AA,1003,CLT,"Charlotte, NC",NC,North Carolina,MCI,"Kansas City, MO",MO,...,0.0,0.0,141.0,808.0,4,0.0,0.0,1.0,0.0,34.0
4,9/1/2025 12:00:00 AM,AA,1003,MCI,"Kansas City, MO",MO,Missouri,CLT,"Charlotte, NC",NC,...,0.0,0.0,142.0,808.0,4,0.0,0.0,0.0,0.0,26.0

In [7]:
df.shape

(9270680, 27)

In [8]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9270680 entries, 0 to 9270679
Data columns (total 27 columns):
 #   Column               Dtype
---  ------               -----
 0   FL_DATE              object
 1   OP_UNIQUE_CARRIER    object
 2   OP_CARRIER_FL_NUM    int64
 3   ORIGIN               object
 4   ORIGIN_CITY_NAME     object
 5   ORIGIN_STATE_ABR     object
 6   ORIGIN_STATE_NM      object
 7   DEST                 object
 8   DEST_CITY_NAME       object
 9   DEST_STATE_ABR       object
 10  DEST_STATE_NM        object
 11  CRS_DEP_TIME         int64
 12  DEP_DELAY            float64
 13  DEP_DELAY_NEW        float64
 14  DEP_DEL15            float64
 15  ARR_DELAY            float64
 16  ARR_DEL15            float64
 17  CANCELLED            float64
 18  DIVERTED             float64
 19  CRS_ELAPSED_TIME     float64
 20  DISTANCE             float64
 21  DISTANCE_GROUP       int64
 22  CARRIER_DELAY        float64
 23  WEATHER_DELAY        float64
 24  NAS_DELAY            float64
 25  SECURITY_DELAY       float64
 26  LATE_AIRCRAFT_DELAY  float64
dtypes: float64(14), int64(3), object(10)
memory usage: 1.9+ GB
None

In [9]:
print(df.head())

                FL_DATE OP_UNIQUE_CARRIER  OP_CARRIER_FL_NUM ORIGIN  \
0  9/1/2025 12:00:00 AM                AA                  1    JFK
1  9/1/2025 12:00:00 AM                AA                 10    LAX
2  9/1/2025 12:00:00 AM                AA               1002    MSN
3  9/1/2025 12:00:00 AM                AA               1003    CLT
4  9/1/2025 12:00:00 AM                AA               1003    MCI

  ORIGIN_CITY_NAME ORIGIN_STATE_ABR ORIGIN_STATE_NM DEST   DEST_CITY_NAME  \
0     New York, NY               NY        New York  LAX  Los Angeles, CA
1  Los Angeles, CA               CA      California  JFK     New York, NY
2      Madison, WI               WI       Wisconsin  CLT    Charlotte, NC
3    Charlotte, NC               NC  North Carolina  MCI  Kansas City, MO
4  Kansas City, MO               MO        Missouri  CLT    Charlotte, NC

  DEST_STATE_ABR  ... CANCELLED  DIVERTED  CRS_ELAPSED_TIME  DISTANCE  \
0             CA  ...       0.0       0.0             359.0    2475.0
1             NY  ...       0.0       0.0             334.0    2475.0
2             NC  ...       0.0       0.0             134.0     708.0
3             MO  ...       0.0       0.0             141.0     808.0
4             NC  ...       0.0       0.0             142.0     808.0

   DISTANCE_GROUP  CARRIER_DELAY  WEATHER_DELAY  NAS_DELAY  SECURITY_DELAY  \
0              10            NaN            NaN        NaN             NaN
1              10            NaN            NaN        NaN             NaN
2               3            NaN            NaN        NaN             NaN
3               4            0.0            0.0        1.0             0.0
4               4            0.0            0.0        0.0             0.0

   LATE_AIRCRAFT_DELAY
0                  NaN
1                  NaN
2                  NaN
3                 34.0
4                 26.0

[5 rows x 27 columns]

In [10]:
print(df.describe())

       OP_CARRIER_FL_NUM  CRS_DEP_TIME     DEP_DELAY  DEP_DELAY_NEW  \
count       9.270680e+06  9.270680e+06  9.113111e+06   9.113111e+06
mean        2.526089e+03  1.323805e+03  1.345565e+01   1.697300e+01
std         1.630858e+03  4.917860e+02  5.784014e+01   5.665760e+01
min         1.000000e+00  1.000000e+00 -1.150000e+02   0.000000e+00
25%         1.207000e+03  9.040000e+02 -6.000000e+00   0.000000e+00
50%         2.275000e+03  1.317000e+03 -2.000000e+00   0.000000e+00
75%         3.662000e+03  1.735000e+03  1.000000e+01   1.000000e+01
max         9.914000e+03  2.400000e+03  4.352000e+03   4.352000e+03

          DEP_DEL15     ARR_DELAY     ARR_DEL15     CANCELLED      DIVERTED  \
count  9.113111e+06  9.082564e+06  9.082564e+06  9.270680e+06  9.270680e+06
mean   2.171583e-01  8.041717e+00  2.207319e-01  1.761295e-02  2.678444e-03
std    4.123113e-01  6.005347e+01  4.147401e-01  1.315399e-01  5.168434e-02
min    0.000000e+00 -1.280000e+02  0.000000e+00  0.000000e+00  0.000000e+00
25%    0.000000e+00 -1.600000e+01  0.000000e+00  0.000000e+00  0.000000e+00
50%    0.000000e+00 -6.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%    0.000000e+00  1.100000e+01  0.000000e+00  0.000000e+00  0.000000e+00
max    1.000000e+00  4.336000e+03  1.000000e+00  1.000000e+00  1.000000e+00

       CRS_ELAPSED_TIME      DISTANCE  DISTANCE_GROUP  CARRIER_DELAY  \
count      9.270677e+06  9.270680e+06    9.270680e+06   2.004812e+06
mean       1.496883e+02  8.451456e+02    3.853087e+00   2.414747e+01
std        7.308230e+01  6.013279e+02    2.355503e+00   7.618385e+01
min       -9.900000e+01  3.100000e+01    1.000000e+00   0.000000e+00
25%        9.500000e+01  4.040000e+02    2.000000e+00   0.000000e+00
50%        1.340000e+02  6.950000e+02    3.000000e+00   2.000000e+00
75%        1.800000e+02  1.081000e+03    5.000000e+00   2.100000e+01
max        1.510000e+03  5.095000e+03    1.100000e+01   4.336000e+03

       WEATHER_DELAY     NAS_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY
count   2.004812e+06  2.004812e+06    2.004812e+06         2.004812e+06
mean    4.669049e+00  1.559351e+01    1.049984e-01         2.837938e+01
std     3.572687e+01  3.609325e+01    3.499826e+00         6.178817e+01
min     0.000000e+00  0.000000e+00    0.000000e+00         0.000000e+00
25%     0.000000e+00  0.000000e+00    0.000000e+00         0.000000e+00
50%     0.000000e+00  1.000000e+00    0.000000e+00         1.000000e+00
75%     0.000000e+00  1.900000e+01    0.000000e+00         3.300000e+01
max     2.394000e+03  1.706000e+03    1.600000e+03         2.425000e+03

In [11]:
missing_values = df.isnull().sum().sort_values(ascending=False)

In [12]:
missing_values

LATE_AIRCRAFT_DELAY    7265868
SECURITY_DELAY         7265868
NAS_DELAY              7265868
WEATHER_DELAY          7265868
CARRIER_DELAY          7265868
ARR_DEL15               188116
ARR_DELAY               188116
DEP_DELAY               157569
DEP_DEL15               157569
DEP_DELAY_NEW           157569
CRS_ELAPSED_TIME             3
DEST_STATE_NM                0
OP_CARRIER_FL_NUM            0
ORIGIN                       0
ORIGIN_CITY_NAME             0
ORIGIN_STATE_ABR             0
DISTANCE_GROUP               0
DISTANCE                     0
DIVERTED                     0
CRS_DEP_TIME                 0
CANCELLED                    0
ORIGIN_STATE_NM              0
DEST                         0
DEST_CITY_NAME               0
OP_UNIQUE_CARRIER            0
DEST_STATE_ABR               0
FL_DATE                      0
dtype: int64

## Data Preprocessing

In [13]:
import numpy as np

In [14]:
# Group 1 - Delay Cause Columns (Fill with 0 - missing simply means that delay cause didn't apply to that flight)
delay_cause_columns = ['LATE_AIRCRAFT_DELAY', 'SECURITY_DELAY', 'NAS_DELAY', 'WEATHER_DELAY', 'CARRIER_DELAY']
df[delay_cause_columns] = df[delay_cause_columns].fillna(0)

In [15]:
# Group 2 - Arrival Columns (Filter out cancelled and diverted flights)
df = df[df['CANCELLED'] == 0]
df = df[df['DIVERTED'] == 0]

In [16]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,...,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,9/1/2025 12:00:00 AM,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,...,0.0,0.0,359.0,2475.0,10,0.0,0.0,0.0,0.0,0.0
1,9/1/2025 12:00:00 AM,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,...,0.0,0.0,334.0,2475.0,10,0.0,0.0,0.0,0.0,0.0
2,9/1/2025 12:00:00 AM,AA,1002,MSN,"Madison, WI",WI,Wisconsin,CLT,"Charlotte, NC",NC,...,0.0,0.0,134.0,708.0,3,0.0,0.0,0.0,0.0,0.0
3,9/1/2025 12:00:00 AM,AA,1003,CLT,"Charlotte, NC",NC,North Carolina,MCI,"Kansas City, MO",MO,...,0.0,0.0,141.0,808.0,4,0.0,0.0,1.0,0.0,34.0
4,9/1/2025 12:00:00 AM,AA,1003,MCI,"Kansas City, MO",MO,Missouri,CLT,"Charlotte, NC",NC,...,0.0,0.0,142.0,808.0,4,0.0,0.0,0.0,0.0,26.0

In [17]:
df.shape

(9082565, 27)

In [18]:
# Group 3 - Departure Target Columns (Drop these rows -- no target variable means the row is useless for training)
df = df[df['DEP_DELAY'].notna()]
df = df[df['DEP_DEL15'].notna()]
df = df[df['DEP_DELAY_NEW'].notna()]

In [19]:
df = df.dropna(subset=['ARR_DELAY'])
df = df.dropna(subset=['ARR_DEL15'])

In [20]:
# Group 4 - CRS_ELAPSED_TIME (Drop the 3 rows with missing values)
df = df[df['CRS_ELAPSED_TIME'].notna()]

In [21]:
df.shape

(9082563, 27)

In [22]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,...,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,9/1/2025 12:00:00 AM,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,...,0.0,0.0,359.0,2475.0,10,0.0,0.0,0.0,0.0,0.0
1,9/1/2025 12:00:00 AM,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,...,0.0,0.0,334.0,2475.0,10,0.0,0.0,0.0,0.0,0.0
2,9/1/2025 12:00:00 AM,AA,1002,MSN,"Madison, WI",WI,Wisconsin,CLT,"Charlotte, NC",NC,...,0.0,0.0,134.0,708.0,3,0.0,0.0,0.0,0.0,0.0
3,9/1/2025 12:00:00 AM,AA,1003,CLT,"Charlotte, NC",NC,North Carolina,MCI,"Kansas City, MO",MO,...,0.0,0.0,141.0,808.0,4,0.0,0.0,1.0,0.0,34.0
4,9/1/2025 12:00:00 AM,AA,1003,MCI,"Kansas City, MO",MO,Missouri,CLT,"Charlotte, NC",NC,...,0.0,0.0,142.0,808.0,4,0.0,0.0,0.0,0.0,26.0

## Feature Engineering

### 1.  Parse FL_DATE into year, month, day of month, and day of week

In [23]:
df["FL_DATE"] = pd.to_datetime(df["FL_DATE"], format="%m/%d/%Y %I:%M:%S %p")

In [24]:
df["FL_DATE"]

0         2025-09-01
1         2025-09-01
2         2025-09-01
3         2025-09-01
4         2025-09-01
             ...
9270674   2025-06-30
9270675   2025-06-30
9270676   2025-06-30
9270677   2025-06-30
9270678   2025-06-30
Name: FL_DATE, Length: 9082563, dtype: datetime64[ns]

In [25]:
df["YEAR"] = df["FL_DATE"].dt.year

In [26]:
df["MONTH"] = df["FL_DATE"].dt.month

In [27]:
df["DAY_OF_MONTH"] = df["FL_DATE"].dt.day

In [28]:
df["DAY_OF_WEEK"] = df["FL_DATE"].dt.dayofweek

In [29]:
df[["DAY_OF_WEEK", "MONTH", "DAY_OF_MONTH", "YEAR"]]

         DAY_OF_WEEK  MONTH  DAY_OF_MONTH  YEAR
0                  0      9             1  2025
1                  0      9             1  2025
2                  0      9             1  2025
3                  0      9             1  2025
4                  0      9             1  2025
...              ...    ...           ...   ...
9270674            0      6            30  2025
9270675            0      6            30  2025
9270676            0      6            30  2025
9270677            0      6            30  2025
9270678            0      6            30  2025

[9082563 rows x 4 columns]

### 2.  Extract departure hour from CRS_DEP_TIME using integer division by 100

In [30]:
# df["CRS_DEP_TIME"]
df["DEPARTURE_HOUR"] = df["CRS_DEP_TIME"] // 100
df["DEPARTURE_MINUTE"] = df["CRS_DEP_TIME"] % 100

### 3.  Create ROUTE feature by combining ORIGIN and DEST

In [31]:
df["ROUTE"] = df["ORIGIN"] + "-" + df["DEST"]
df["ROUTE"].head()

0    JFK-LAX
1    LAX-JFK
2    MSN-CLT
3    CLT-MCI
4    MCI-CLT
Name: ROUTE, dtype: object

### 4.  Create IsHolidayPeriod using your holiday function

In [32]:
def isHolidayPeriod(date):
    # df["MONTH"] = df["FL_DATE"].dt.month
    # df["DAY_OF_MONTH"] = df["FL_DATE"].dt.day
    
    # MLK Day
    if date.month == 1 and 15 <= date.day <= 20:
        return 1

    # Presidents Day
    if date.month == 2 and 13 <= date.day <= 17:
        return 1
    
    # Spring Break
    if (date.month == 3 and date.day >= 15) or (date.month == 4 and date.day <= 15):
        return 1
    
    # Memorial Day 
    if date.month == 5 and 23 <= date.day <= 27:
        return 1
    
    # Fourth of July
    if date.month == 7 and 1 <= date.day <= 7:
        return 1
    
    # Labor Day
    if (date.month == 8 and date.day >= 29) or (date.month == 9 and date.day <= 2):
        return 1
    
    # Thanksgiving (Nov 20 – Dec 1)
    if (date.month == 11 and date.day >= 20) or (date.month == 12 and date.day <= 1):
        return 1

    # Christmas & New Year (Dec 20 – Jan 5)
    if (date.month == 12 and date.day >= 20) or (date.month == 1 and date.day <= 5):
        return 1

    return 0

In [33]:
df['IS_HOLIDAY_PERIOD'] = df['FL_DATE'].apply(isHolidayPeriod)

### 5.  Create target variable DEP_DELAY from DEP_DEL_15

In [34]:
df['DELAYED'] = (df['DEP_DELAY'] > 15).astype(int)

### 6.  Drop FL DATE, DEP_DEL15, ARR_DEL15, ARR_DELAY, CANCELLED, DIVERTED

In [35]:
'FL_DATE' in df, 'DEP_DEL15' in df, 'ARR_DEL15' in df, 'ARR_DELAY' in df, 'CANCELLED' in df, 'DIVERTED' in df

(True, True, True, True, True, True)

In [36]:
df = df.drop(columns=['FL_DATE', 'DEP_DEL15', 'ARR_DEL15', 'ARR_DELAY', 'CANCELLED', 'DIVERTED'])

### 7.  Label encode OP_UNIQUE_CARRIER, ORIGIN_STATE_ABR, DEST_STATE_ABR

In [47]:
from sklearn.preprocessing import LabelEncoder
import joblib

In [44]:
df[['OP_UNIQUE_CARRIER', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR']].head()

  OP_UNIQUE_CARRIER ORIGIN_STATE_ABR DEST_STATE_ABR
0                AA               NY             CA
1                AA               CA             NY
2                AA               WI             NC
3                AA               NC             MO
4                AA               MO             NC

In [48]:
le_carrier = LabelEncoder()
le_origin_state = LabelEncoder()
le_dest_state = LabelEncoder()

df['OP_UNIQUE_CARRIER'] = le_carrier.fit_transform(df['OP_UNIQUE_CARRIER'])
df['ORIGIN_STATE_ABR'] = le_origin_state.fit_transform(df['ORIGIN_STATE_ABR'])
df['DEST_STATE_ABR'] = le_dest_state.fit_transform(df['DEST_STATE_ABR'])

In [54]:
df[['OP_UNIQUE_CARRIER', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR']].head()

   OP_UNIQUE_CARRIER  ORIGIN_STATE_ABR  DEST_STATE_ABR
0                  0                32               4
1                  0                 4              32
2                  0                49              25
3                  0                25              22
4                  0                22              25

In [55]:
joblib.dump(le_carrier, '../encodings/le_carrier.pkl')
joblib.dump(le_origin_state, '../encodings/le_origin_state.pkl')
joblib.dump(le_dest_state, '../encodings/le_dest_state.pkl')

['../encodings/le_dest_state.pkl']

### 8.  Define features X and target y -- Feature Selection

### 9.  Train/val/test split -- 70/15/15

In [40]:
from sklearn.model_selection import train_test_split

### 10. Target encode ORIGIN, DEST, ROUTE on training data only

### 11. Saved processed data to parquet