In [138]:
import pandas as pd
import glob
import os

## Data Loading

In [139]:
all_dfs = []
for filename in glob.glob("../data/*.csv"):
    new_df = pd.read_csv(filename)
    all_dfs.append(new_df)
df = pd.concat(all_dfs)

In [140]:
df.to_parquet("../data/raw_data.parquet", index=False)

In [141]:
df = pd.read_parquet("../data/raw_data.parquet")

In [142]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,...,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,9/1/2025 12:00:00 AM,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,...,0.0,0.0,359.0,2475.0,10,NaN,NaN,NaN,NaN,NaN
1,9/1/2025 12:00:00 AM,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,...,0.0,0.0,334.0,2475.0,10,NaN,NaN,NaN,NaN,NaN
2,9/1/2025 12:00:00 AM,AA,1002,MSN,"Madison, WI",WI,Wisconsin,CLT,"Charlotte, NC",NC,...,0.0,0.0,134.0,708.0,3,NaN,NaN,NaN,NaN,NaN
3,9/1/2025 12:00:00 AM,AA,1003,CLT,"Charlotte, NC",NC,North Carolina,MCI,"Kansas City, MO",MO,...,0.0,0.0,141.0,808.0,4,0.0,0.0,1.0,0.0,34.0
4,9/1/2025 12:00:00 AM,AA,1003,MCI,"Kansas City, MO",MO,Missouri,CLT,"Charlotte, NC",NC,...,0.0,0.0,142.0,808.0,4,0.0,0.0,0.0,0.0,26.0

In [143]:
df.shape

(9270680, 27)

In [144]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9270680 entries, 0 to 9270679
Data columns (total 27 columns):
 #   Column               Dtype
---  ------               -----
 0   FL_DATE              object
 1   OP_UNIQUE_CARRIER    object
 2   OP_CARRIER_FL_NUM    int64
 3   ORIGIN               object
 4   ORIGIN_CITY_NAME     object
 5   ORIGIN_STATE_ABR     object
 6   ORIGIN_STATE_NM      object
 7   DEST                 object
 8   DEST_CITY_NAME       object
 9   DEST_STATE_ABR       object
 10  DEST_STATE_NM        object
 11  CRS_DEP_TIME         int64
 12  DEP_DELAY            float64
 13  DEP_DELAY_NEW        float64
 14  DEP_DEL15            float64
 15  ARR_DELAY            float64
 16  ARR_DEL15            float64
 17  CANCELLED            float64
 18  DIVERTED             float64
 19  CRS_ELAPSED_TIME     float64
 20  DISTANCE             float64
 21  DISTANCE_GROUP       int64
 22  CARRIER_DELAY        float64
 23  WEATHER_DELAY        float64
 24  NAS_DELAY            float64
 25  SECURITY_DELAY       float64
 26  LATE_AIRCRAFT_DELAY  float64
dtypes: float64(14), int64(3), object(10)
memory usage: 1.9+ GB
None

In [145]:
print(df.head())

                FL_DATE OP_UNIQUE_CARRIER  OP_CARRIER_FL_NUM ORIGIN  \
0  9/1/2025 12:00:00 AM                AA                  1    JFK
1  9/1/2025 12:00:00 AM                AA                 10    LAX
2  9/1/2025 12:00:00 AM                AA               1002    MSN
3  9/1/2025 12:00:00 AM                AA               1003    CLT
4  9/1/2025 12:00:00 AM                AA               1003    MCI

  ORIGIN_CITY_NAME ORIGIN_STATE_ABR ORIGIN_STATE_NM DEST   DEST_CITY_NAME  \
0     New York, NY               NY        New York  LAX  Los Angeles, CA
1  Los Angeles, CA               CA      California  JFK     New York, NY
2      Madison, WI               WI       Wisconsin  CLT    Charlotte, NC
3    Charlotte, NC               NC  North Carolina  MCI  Kansas City, MO
4  Kansas City, MO               MO        Missouri  CLT    Charlotte, NC

  DEST_STATE_ABR  ... CANCELLED  DIVERTED  CRS_ELAPSED_TIME  DISTANCE  \
0             CA  ...       0.0       0.0             359.0    2475.0
1             NY  ...       0.0       0.0             334.0    2475.0
2             NC  ...       0.0       0.0             134.0     708.0
3             MO  ...       0.0       0.0             141.0     808.0
4             NC  ...       0.0       0.0             142.0     808.0

   DISTANCE_GROUP  CARRIER_DELAY  WEATHER_DELAY  NAS_DELAY  SECURITY_DELAY  \
0              10            NaN            NaN        NaN             NaN
1              10            NaN            NaN        NaN             NaN
2               3            NaN            NaN        NaN             NaN
3               4            0.0            0.0        1.0             0.0
4               4            0.0            0.0        0.0             0.0

   LATE_AIRCRAFT_DELAY
0                  NaN
1                  NaN
2                  NaN
3                 34.0
4                 26.0

[5 rows x 27 columns]

In [146]:
print(df.describe())

       OP_CARRIER_FL_NUM  CRS_DEP_TIME     DEP_DELAY  DEP_DELAY_NEW  \
count       9.270680e+06  9.270680e+06  9.113111e+06   9.113111e+06
mean        2.526089e+03  1.323805e+03  1.345565e+01   1.697300e+01
std         1.630858e+03  4.917860e+02  5.784014e+01   5.665760e+01
min         1.000000e+00  1.000000e+00 -1.150000e+02   0.000000e+00
25%         1.207000e+03  9.040000e+02 -6.000000e+00   0.000000e+00
50%         2.275000e+03  1.317000e+03 -2.000000e+00   0.000000e+00
75%         3.662000e+03  1.735000e+03  1.000000e+01   1.000000e+01
max         9.914000e+03  2.400000e+03  4.352000e+03   4.352000e+03

          DEP_DEL15     ARR_DELAY     ARR_DEL15     CANCELLED      DIVERTED  \
count  9.113111e+06  9.082564e+06  9.082564e+06  9.270680e+06  9.270680e+06
mean   2.171583e-01  8.041717e+00  2.207319e-01  1.761295e-02  2.678444e-03
std    4.123113e-01  6.005347e+01  4.147401e-01  1.315399e-01  5.168434e-02
min    0.000000e+00 -1.280000e+02  0.000000e+00  0.000000e+00  0.000000e+00
25%    0.000000e+00 -1.600000e+01  0.000000e+00  0.000000e+00  0.000000e+00
50%    0.000000e+00 -6.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%    0.000000e+00  1.100000e+01  0.000000e+00  0.000000e+00  0.000000e+00
max    1.000000e+00  4.336000e+03  1.000000e+00  1.000000e+00  1.000000e+00

       CRS_ELAPSED_TIME      DISTANCE  DISTANCE_GROUP  CARRIER_DELAY  \
count      9.270677e+06  9.270680e+06    9.270680e+06   2.004812e+06
mean       1.496883e+02  8.451456e+02    3.853087e+00   2.414747e+01
std        7.308230e+01  6.013279e+02    2.355503e+00   7.618385e+01
min       -9.900000e+01  3.100000e+01    1.000000e+00   0.000000e+00
25%        9.500000e+01  4.040000e+02    2.000000e+00   0.000000e+00
50%        1.340000e+02  6.950000e+02    3.000000e+00   2.000000e+00
75%        1.800000e+02  1.081000e+03    5.000000e+00   2.100000e+01
max        1.510000e+03  5.095000e+03    1.100000e+01   4.336000e+03

       WEATHER_DELAY     NAS_DELAY  SECURITY_DELAY  LATE_AIRCRAFT_DELAY
count   2.004812e+06  2.004812e+06    2.004812e+06         2.004812e+06
mean    4.669049e+00  1.559351e+01    1.049984e-01         2.837938e+01
std     3.572687e+01  3.609325e+01    3.499826e+00         6.178817e+01
min     0.000000e+00  0.000000e+00    0.000000e+00         0.000000e+00
25%     0.000000e+00  0.000000e+00    0.000000e+00         0.000000e+00
50%     0.000000e+00  1.000000e+00    0.000000e+00         1.000000e+00
75%     0.000000e+00  1.900000e+01    0.000000e+00         3.300000e+01
max     2.394000e+03  1.706000e+03    1.600000e+03         2.425000e+03

In [147]:
missing_values = df.isnull().sum().sort_values(ascending=False)

In [148]:
missing_values

LATE_AIRCRAFT_DELAY    7265868
SECURITY_DELAY         7265868
NAS_DELAY              7265868
WEATHER_DELAY          7265868
CARRIER_DELAY          7265868
ARR_DEL15               188116
ARR_DELAY               188116
DEP_DELAY               157569
DEP_DEL15               157569
DEP_DELAY_NEW           157569
CRS_ELAPSED_TIME             3
DEST_STATE_NM                0
OP_CARRIER_FL_NUM            0
ORIGIN                       0
ORIGIN_CITY_NAME             0
ORIGIN_STATE_ABR             0
DISTANCE_GROUP               0
DISTANCE                     0
DIVERTED                     0
CRS_DEP_TIME                 0
CANCELLED                    0
ORIGIN_STATE_NM              0
DEST                         0
DEST_CITY_NAME               0
OP_UNIQUE_CARRIER            0
DEST_STATE_ABR               0
FL_DATE                      0
dtype: int64

## Data Preprocessing

In [149]:
import numpy as np

In [150]:
# Group 1 - Delay Cause Columns (Fill with 0 - missing simply means that delay cause didn't apply to that flight)
delay_cause_columns = ['LATE_AIRCRAFT_DELAY', 'SECURITY_DELAY', 'NAS_DELAY', 'WEATHER_DELAY', 'CARRIER_DELAY']
df[delay_cause_columns] = df[delay_cause_columns].fillna(0)

In [151]:
# Group 2 - Arrival Columns (Filter out cancelled and diverted flights)
df = df[df['CANCELLED'] == 0]
df = df[df['DIVERTED'] == 0]

In [152]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,...,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,9/1/2025 12:00:00 AM,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,...,0.0,0.0,359.0,2475.0,10,0.0,0.0,0.0,0.0,0.0
1,9/1/2025 12:00:00 AM,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,...,0.0,0.0,334.0,2475.0,10,0.0,0.0,0.0,0.0,0.0
2,9/1/2025 12:00:00 AM,AA,1002,MSN,"Madison, WI",WI,Wisconsin,CLT,"Charlotte, NC",NC,...,0.0,0.0,134.0,708.0,3,0.0,0.0,0.0,0.0,0.0
3,9/1/2025 12:00:00 AM,AA,1003,CLT,"Charlotte, NC",NC,North Carolina,MCI,"Kansas City, MO",MO,...,0.0,0.0,141.0,808.0,4,0.0,0.0,1.0,0.0,34.0
4,9/1/2025 12:00:00 AM,AA,1003,MCI,"Kansas City, MO",MO,Missouri,CLT,"Charlotte, NC",NC,...,0.0,0.0,142.0,808.0,4,0.0,0.0,0.0,0.0,26.0

In [153]:
df.shape

(9082565, 27)

In [154]:
# Group 3 - Departure Target Columns (Drop these rows -- no target variable means the row is useless for training)
df = df[df['DEP_DELAY'].notna()]
df = df[df['DEP_DEL15'].notna()]
df = df[df['DEP_DELAY_NEW'].notna()]

In [155]:
df = df.dropna(subset=['ARR_DELAY'])
df = df.dropna(subset=['ARR_DEL15'])

In [156]:
# Group 4 - CRS_ELAPSED_TIME (Drop the 3 rows with missing values)
df = df[df['CRS_ELAPSED_TIME'].notna()]

In [157]:
df.shape

(9082563, 27)

In [158]:
df.head()

,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,...,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,9/1/2025 12:00:00 AM,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,...,0.0,0.0,359.0,2475.0,10,0.0,0.0,0.0,0.0,0.0
1,9/1/2025 12:00:00 AM,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,...,0.0,0.0,334.0,2475.0,10,0.0,0.0,0.0,0.0,0.0
2,9/1/2025 12:00:00 AM,AA,1002,MSN,"Madison, WI",WI,Wisconsin,CLT,"Charlotte, NC",NC,...,0.0,0.0,134.0,708.0,3,0.0,0.0,0.0,0.0,0.0
3,9/1/2025 12:00:00 AM,AA,1003,CLT,"Charlotte, NC",NC,North Carolina,MCI,"Kansas City, MO",MO,...,0.0,0.0,141.0,808.0,4,0.0,0.0,1.0,0.0,34.0
4,9/1/2025 12:00:00 AM,AA,1003,MCI,"Kansas City, MO",MO,Missouri,CLT,"Charlotte, NC",NC,...,0.0,0.0,142.0,808.0,4,0.0,0.0,0.0,0.0,26.0

## Feature Engineering

### 1.  Parse FL_DATE into year, month, day of month, and day of week

In [159]:
df["FL_DATE"] = pd.to_datetime(df["FL_DATE"], format="%m/%d/%Y %I:%M:%S %p")

In [160]:
df["FL_DATE"]

0         2025-09-01
1         2025-09-01
2         2025-09-01
3         2025-09-01
4         2025-09-01
             ...
9270674   2025-06-30
9270675   2025-06-30
9270676   2025-06-30
9270677   2025-06-30
9270678   2025-06-30
Name: FL_DATE, Length: 9082563, dtype: datetime64[ns]

In [161]:
df["YEAR"] = df["FL_DATE"].dt.year

In [162]:
df["MONTH"] = df["FL_DATE"].dt.month

In [163]:
df["DAY_OF_MONTH"] = df["FL_DATE"].dt.day

In [164]:
df["DAY_OF_WEEK"] = df["FL_DATE"].dt.dayofweek

In [165]:
df[["DAY_OF_WEEK", "MONTH", "DAY_OF_MONTH", "YEAR"]]

         DAY_OF_WEEK  MONTH  DAY_OF_MONTH  YEAR
0                  0      9             1  2025
1                  0      9             1  2025
2                  0      9             1  2025
3                  0      9             1  2025
4                  0      9             1  2025
...              ...    ...           ...   ...
9270674            0      6            30  2025
9270675            0      6            30  2025
9270676            0      6            30  2025
9270677            0      6            30  2025
9270678            0      6            30  2025

[9082563 rows x 4 columns]

### 2.  Extract departure hour from CRS_DEP_TIME using integer division by 100

In [166]:
df["DEPARTURE_HOUR"] = df["CRS_DEP_TIME"] // 100
df["DEPARTURE_MINUTE"] = df["CRS_DEP_TIME"] % 100
df = df.drop(columns=["CRS_DEP_TIME"])

### 3.  Create ROUTE feature by combining ORIGIN and DEST

In [167]:
df["ROUTE"] = df["ORIGIN"] + "-" + df["DEST"]
df["ROUTE"].head()

0    JFK-LAX
1    LAX-JFK
2    MSN-CLT
3    CLT-MCI
4    MCI-CLT
Name: ROUTE, dtype: object

### 4.  Create IsHolidayPeriod using your holiday function

In [168]:
def isHolidayPeriod(date):
    # df["MONTH"] = df["FL_DATE"].dt.month
    # df["DAY_OF_MONTH"] = df["FL_DATE"].dt.day
    
    # MLK Day
    if date.month == 1 and 15 <= date.day <= 20:
        return 1

    # Presidents Day
    if date.month == 2 and 13 <= date.day <= 17:
        return 1
    
    # Spring Break
    if (date.month == 3 and date.day >= 15) or (date.month == 4 and date.day <= 15):
        return 1
    
    # Memorial Day 
    if date.month == 5 and 23 <= date.day <= 27:
        return 1
    
    # Fourth of July
    if date.month == 7 and 1 <= date.day <= 7:
        return 1
    
    # Labor Day
    if (date.month == 8 and date.day >= 29) or (date.month == 9 and date.day <= 2):
        return 1
    
    # Thanksgiving (Nov 20 – Dec 1)
    if (date.month == 11 and date.day >= 20) or (date.month == 12 and date.day <= 1):
        return 1

    # Christmas & New Year (Dec 20 – Jan 5)
    if (date.month == 12 and date.day >= 20) or (date.month == 1 and date.day <= 5):
        return 1

    return 0

In [169]:
df['IS_HOLIDAY_PERIOD'] = df['FL_DATE'].apply(isHolidayPeriod)

### 5.  Create target variable DEP_DELAY from DEP_DEL_15

In [170]:
df['DELAYED'] = (df['DEP_DELAY'] > 15).astype(int)

### 6.  Drop FL DATE, DEP_DEL15, ARR_DEL15, ARR_DELAY, CANCELLED, DIVERTED

In [171]:
'FL_DATE' in df, 'DEP_DEL15' in df, 'ARR_DEL15' in df, 'ARR_DELAY' in df, 'CANCELLED' in df, 'DIVERTED' in df

(True, True, True, True, True, True)

In [172]:
df = df.drop(columns=['FL_DATE', 'DEP_DEL15', 'ARR_DEL15', 'ARR_DELAY', 'CANCELLED', 'DIVERTED'])

### 7.  Label encode OP_UNIQUE_CARRIER, ORIGIN_STATE_ABR, DEST_STATE_ABR

In [173]:
from sklearn.preprocessing import LabelEncoder
import joblib

In [174]:
df[['OP_UNIQUE_CARRIER', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR']].head()

  OP_UNIQUE_CARRIER ORIGIN_STATE_ABR DEST_STATE_ABR
0                AA               NY             CA
1                AA               CA             NY
2                AA               WI             NC
3                AA               NC             MO
4                AA               MO             NC

In [175]:
le_carrier = LabelEncoder()
le_origin_state = LabelEncoder()
le_dest_state = LabelEncoder()

df['OP_UNIQUE_CARRIER'] = le_carrier.fit_transform(df['OP_UNIQUE_CARRIER'])
df['ORIGIN_STATE_ABR'] = le_origin_state.fit_transform(df['ORIGIN_STATE_ABR'])
df['DEST_STATE_ABR'] = le_dest_state.fit_transform(df['DEST_STATE_ABR'])

In [176]:
df[['OP_UNIQUE_CARRIER', 'ORIGIN_STATE_ABR', 'DEST_STATE_ABR']].head()

   OP_UNIQUE_CARRIER  ORIGIN_STATE_ABR  DEST_STATE_ABR
0                  0                32               4
1                  0                 4              32
2                  0                49              25
3                  0                25              22
4                  0                22              25

In [177]:
joblib.dump(le_carrier, '../encodings/le_carrier.pkl')
joblib.dump(le_origin_state, '../encodings/le_origin_state.pkl')
joblib.dump(le_dest_state, '../encodings/le_dest_state.pkl')

['../encodings/le_dest_state.pkl']

### 8.  Define features X and target y -- Feature Selection

In [178]:
y = df["DELAYED"]

In [179]:
correlation_matrix = df.corr(numeric_only=True, method='spearman')
correlation_matrix

,OP_UNIQUE_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_STATE_ABR,DEST_STATE_ABR,DEP_DELAY,DEP_DELAY_NEW,CRS_ELAPSED_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,...,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,YEAR,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,DEPARTURE_HOUR,DEPARTURE_MINUTE,IS_HOLIDAY_PERIOD,DELAYED
OP_UNIQUE_CARRIER,1.000000,0.269893,-0.026916,-0.026653,0.043496,0.012831,-0.195294,-0.187854,-0.188876,-0.022210,...,-0.004950,-0.004536,-0.002345,0.000735,-0.000043,-0.003810,-0.007538,-0.009393,0.001710,-0.010214
OP_CARRIER_FL_NUM,0.269893,1.000000,0.044098,0.049921,-0.054966,-0.026878,-0.320864,-0.362193,-0.359256,0.002285,...,-0.005926,-0.001860,0.009968,0.004904,0.000785,0.000616,0.023033,0.005780,-0.000546,0.001742
ORIGIN_STATE_ABR,-0.026916,0.044098,1.000000,0.013719,-0.004865,0.000684,-0.007074,-0.033375,-0.040283,0.006570,...,-0.000829,0.007726,-0.008576,0.011711,-0.001141,-0.005162,-0.012519,0.001890,-0.007652,0.007333
DEST_STATE_ABR,-0.026653,0.049921,0.013719,1.000000,-0.009168,-0.001313,-0.033183,-0.033370,-0.040284,0.001352,...,0.001818,0.011242,-0.008640,0.011753,-0.001236,-0.005361,0.003029,-0.003760,-0.007632,0.005608
DEP_DELAY,0.043496,-0.054966,-0.004865,-0.009168,1.000000,0.872249,0.054574,0.065691,0.063462,0.469570,...,0.035916,0.495372,-0.009957,0.025627,0.003839,0.040049,0.204811,0.055249,0.027275,0.705905
DEP_DELAY_NEW,0.012831,-0.026878,0.000684,-0.001313,0.872249,1.000000,0.036800,0.042451,0.040666,0.537585,...,0.041176,0.567925,-0.001872,0.027475,0.002797,0.034978,0.227731,0.055695,0.024281,0.809292
CRS_ELAPSED_TIME,-0.195294,-0.320864,-0.007074,-0.033183,0.054574,0.036800,1.000000,0.979827,0.967207,0.014983,...,0.005102,-0.006104,0.023012,-0.021772,-0.000650,0.009399,-0.033747,-0.000238,0.019037,0.014881
DISTANCE,-0.187854,-0.362193,-0.033375,-0.033370,0.065691,0.042451,0.979827,1.000000,0.986522,0.017856,...,0.005712,-0.001319,0.004471,-0.007424,0.000278,0.010396,-0.027044,0.006106,0.014595,0.015374
DISTANCE_GROUP,-0.188876,-0.359256,-0.040283,-0.040284,0.063462,0.040666,0.967207,0.986522,1.000000,0.017075,...,0.005504,-0.003098,0.004711,-0.007623,0.000323,0.010284,-0.026766,0.007138,0.014529,0.013999
CARRIER_DELAY,-0.022210,0.002285,0.006570,0.001352,0.469570,0.537585,0.014983,0.017856,0.017075,1.000000,...,-0.003522,0.387193,-0.000040,0.015879,0.002547,0.025408,0.103780,0.024346,0.017184,0.585310
WEATHER_DELAY,-0.021227,0.033823,0.012283,0.014794,0.168949,0.193675,-0.017174,-0.020968,-0.020711,-0.029624,...,-0.002562,0.102473,-0.005368,-0.002790,0.002545,0.006611,0.037107,0.007209,-0.000447,0.205052
NAS_DELAY,-0.021742,-0.007407,0.016644,0.009681,0.327887,0.358382,0.037356,0.032698,0.031088,0.290158,...,0.028537,0.292387,-0.013740,0.016174,-0.007620,0.021762,0.083063,0.020651,0.009742,0.347070
SECURITY_DELAY,-0.004950,-0.005926,-0.000829,0.001818,0.035916,0.041176,0.005102,0.005712,0.005504,-0.003522,...,1.000000,0.026158,0.001878,-0.000840,-0.000122,0.003696,0.006701,0.000843,0.003828,0.043961
LATE_AIRCRAFT_DELAY,-0.004536,-0.001860,0.007726,0.011242,0.495372,0.567925,-0.006104,-0.001319,-0.003098,0.387193,...,0.026158,1.000000,-0.009043,0.028039,0.000846,0.024798,0.202601,0.049554,0.016871,0.635808
YEAR,-0.002345,0.009968,-0.008576,-0.008640,-0.009957,-0.001872,0.023012,0.004471,0.004711,-0.000040,...,0.001878,-0.009043,1.000000,-0.507294,-0.014936,0.001261,0.000398,0.000093,0.162623,-0.002030
MONTH,0.000735,0.004904,0.011711,0.011753,0.025627,0.027475,-0.021772,-0.007424,-0.007623,0.015879,...,-0.000840,0.028039,-0.507294,1.000000,0.016091,-0.009205,-0.000674,0.001193,-0.151349,0.023087
DAY_OF_MONTH,-0.000043,0.000785,-0.001141,-0.001236,0.003839,0.002797,-0.000650,0.000278,0.000323,0.002547,...,-0.000122,0.000846,-0.014936,0.016091,1.000000,0.000203,-0.000346,0.000402,0.045041,0.001539
DAY_OF_WEEK,-0.003810,0.000616,-0.005162,-0.005361,0.040049,0.034978,0.009399,0.010396,0.010284,0.025408,...,0.003696,0.024798,0.001261,-0.009205,0.000203,1.000000,0.004493,0.000186,0.032175,0.028634
DEPARTURE_HOUR,-0.007538,0.023033,-0.012519,0.003029,0.204811,0.227731,-0.033747,-0.027044,-0.026766,0.103780,...,0.006701,0.202601,0.000398,-0.000674,-0.000346,0.004493,1.000000,0.172263,0.003500,0.197426
DEPARTURE_MINUTE,-0.009393,0.005780,0.001890,-0.003760,0.055249,0.055695,-0.000238,0.006106,0.007138,0.024346,...,0.000843,0.049554,0.000093,0.001193,0.000402,0.000186,0.172263,1.000000,-0.000237,0.045069
IS_HOLIDAY_PERIOD,0.001710,-0.000546,-0.007652,-0.007632,0.027275,0.024281,0.019037,0.014595,0.014529,0.017184,...,0.003828,0.016871,0.162623,-0.151349,0.045041,0.032175,0.003500,-0.000237,1.000000,0.019809
DELAYED,-0.010214,0.001742,0.007333,0.005608,0.705905,0.809292,0.014881,0.015374,0.013999,0.585310,...,0.043961,0.635808,-0.002030,0.023087,0.001539,0.028634,0.197426,0.045069,0.019809,1.000000

In [180]:
numerical_columns = correlation_matrix['DELAYED'].sort_values(ascending=False)

In [181]:
numerical_columns

DELAYED                1.000000
DEP_DELAY_NEW          0.809292
DEP_DELAY              0.705905
LATE_AIRCRAFT_DELAY    0.635808
CARRIER_DELAY          0.585310
NAS_DELAY              0.347070
WEATHER_DELAY          0.205052
DEPARTURE_HOUR         0.197426
DEPARTURE_MINUTE       0.045069
SECURITY_DELAY         0.043961
DAY_OF_WEEK            0.028634
MONTH                  0.023087
IS_HOLIDAY_PERIOD      0.019809
DISTANCE               0.015374
CRS_ELAPSED_TIME       0.014881
DISTANCE_GROUP         0.013999
ORIGIN_STATE_ABR       0.007333
DEST_STATE_ABR         0.005608
OP_CARRIER_FL_NUM      0.001742
DAY_OF_MONTH           0.001539
YEAR                  -0.002030
OP_UNIQUE_CARRIER     -0.010214
Name: DELAYED, dtype: float64

In [182]:
# Drop the Delay columns
df = df.drop(columns=['DEP_DELAY_NEW', 'DEP_DELAY', 'LATE_AIRCRAFT_DELAY', 'CARRIER_DELAY', 'NAS_DELAY', 'WEATHER_DELAY', 'SECURITY_DELAY'])

In [183]:
updated_correlation_matrix = df.corr(numeric_only=True, method='spearman')
updated_numerical_columns = updated_correlation_matrix['DELAYED'].sort_values(ascending=False)
updated_numerical_columns

DELAYED              1.000000
DEPARTURE_HOUR       0.197426
DEPARTURE_MINUTE     0.045069
DAY_OF_WEEK          0.028634
MONTH                0.023087
IS_HOLIDAY_PERIOD    0.019809
DISTANCE             0.015374
CRS_ELAPSED_TIME     0.014881
DISTANCE_GROUP       0.013999
ORIGIN_STATE_ABR     0.007333
DEST_STATE_ABR       0.005608
OP_CARRIER_FL_NUM    0.001742
DAY_OF_MONTH         0.001539
YEAR                -0.002030
OP_UNIQUE_CARRIER   -0.010214
Name: DELAYED, dtype: float64

In [184]:
updated_numerical_columns = updated_numerical_columns.drop(['DELAYED'])

In [185]:
updated_numerical_columns = updated_numerical_columns[updated_numerical_columns >= 0]

In [186]:
updated_numerical_columns

DEPARTURE_HOUR       0.197426
DEPARTURE_MINUTE     0.045069
DAY_OF_WEEK          0.028634
MONTH                0.023087
IS_HOLIDAY_PERIOD    0.019809
DISTANCE             0.015374
CRS_ELAPSED_TIME     0.014881
DISTANCE_GROUP       0.013999
ORIGIN_STATE_ABR     0.007333
DEST_STATE_ABR       0.005608
OP_CARRIER_FL_NUM    0.001742
DAY_OF_MONTH         0.001539
Name: DELAYED, dtype: float64

In [187]:
updated_numerical_columns = updated_numerical_columns.drop(['DISTANCE_GROUP'])

In [188]:
updated_numerical_columns

DEPARTURE_HOUR       0.197426
DEPARTURE_MINUTE     0.045069
DAY_OF_WEEK          0.028634
MONTH                0.023087
IS_HOLIDAY_PERIOD    0.019809
DISTANCE             0.015374
CRS_ELAPSED_TIME     0.014881
ORIGIN_STATE_ABR     0.007333
DEST_STATE_ABR       0.005608
OP_CARRIER_FL_NUM    0.001742
DAY_OF_MONTH         0.001539
Name: DELAYED, dtype: float64

In [189]:
numerical_features = updated_numerical_columns.index.tolist()

In [190]:
numerical_features.append('ORIGIN')
numerical_features.append('DEST')
numerical_features.append('ROUTE')

In [191]:
X = df[numerical_features]

### 8.  Train/val/test split -- 70/15/15

In [192]:
from sklearn.model_selection import train_test_split

In [193]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=1234)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=1234)

In [194]:
print(f"Train: {X_train.shape[0]:,} rows")
print(f"Validation: {X_val.shape[0]:,} rows")
print(f"Test: {X_test.shape[0]:,} rows")

Train: 6,357,794 rows
Validation: 1,362,384 rows
Test: 1,362,385 rows

### 10. Target encode ORIGIN, DEST, ROUTE on training data only

In [195]:
from sklearn.preprocessing import TargetEncoder

In [196]:
te_origin = TargetEncoder()
te_dest = TargetEncoder()
te_route = TargetEncoder()

In [197]:
# Fit transform the training data
X_train['ORIGIN_ENCODED'] = te_origin.fit_transform(X_train[['ORIGIN']], y_train)
X_train['DEST_ENCODED'] = te_dest.fit_transform(X_train[['DEST']], y_train)
X_train['ROUTE_ENCODED'] = te_route.fit_transform(X_train[['ROUTE']], y_train)

X_val['ORIGIN_ENCODED'] = te_origin.transform(X_val[['ORIGIN']])
X_val['DEST_ENCODED'] = te_dest.transform(X_val[['DEST']])
X_val['ROUTE_ENCODED'] = te_route.transform(X_val[['ROUTE']])

X_test['ORIGIN_ENCODED'] = te_origin.transform(X_test[['ORIGIN']])
X_test['DEST_ENCODED'] = te_dest.transform(X_test[['DEST']])
X_test['ROUTE_ENCODED'] = te_route.transform(X_test[['ROUTE']])

X_train = X_train.drop(columns=['ORIGIN', 'DEST', 'ROUTE'])
X_val = X_val.drop(columns=['ORIGIN', 'DEST', 'ROUTE'])
X_test = X_test.drop(columns=['ORIGIN', 'DEST', 'ROUTE'])

### 11. Saved processed data to parquet

In [198]:
# Saving the origin, dest, and route target encoders
joblib.dump(te_origin, '../encodings/origin_te.pkl')
joblib.dump(te_dest, '../encodings/dest_te.pkl')
joblib.dump(te_route, '../encodings/route_te.pkl')

['../encodings/route_te.pkl']

In [199]:
# Saving the training, validation, and testing data
X_train.to_parquet('../data/X_train.parquet')
X_val.to_parquet('../data/X_val.parquet')
X_test.to_parquet('../data/X_test.parquet')
y_train.to_frame().to_parquet('../data/y_train.parquet')
y_val.to_frame().to_parquet('../data/y_val.parquet')
y_test.to_frame().to_parquet('../data/y_test.parquet')

## Modeling

In [201]:
import lightgbm as lgbm
import optuna

In [ ]:
params = {
  
  "n_estimators": trial.suggest_int("n_estimators", [100, 500, 1000]),
        "learning_rate": trial.suggest_int("learning_rate", [0.01, 0.05, 0.1]),
        "max_depth": trial.suggest_int("max_depth", [5, 7, 10]),
        "num_leaves": trial.suggest_int("num_leaves", [31, 50, 100]),
        "class_weight": "balanced"
}